name: flutter_ffmpeg
description: Flutter plugin to run FFmpeg on mobile platforms. Supports iOS and Android.
version: 0.3.0
homepage: https://github.com/tanersener/flutter-ffmpeg

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^1.6.16
  path: ^1.7.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterFFmpegPlugin